name: CreateMDRelease

on:
  push:
    branches: [main]

env:
  VERSION: 1.1.${{ github.run_number }}

jobs:
  ReleaseToGithub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: release
        uses: actions/create-release@v1
        id: README-TEMPLATE-release
        with:
          draft: false
          prerelease: false
          release_name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          body_path: .github/Changelog.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
